[package]
name = "cluedo"
version = "0.1.0"
authors = ["Kyle Cooke <kyle@playerdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "*"
rand = "*"
